# Generated by Django 4.0.5 on 2022-06-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite_user_created_at_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_favorite', to='api.favorite'),
        ),
    ]
