# Generated by Django 4.0.5 on 2022-06-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
