# Generated by Django 4.0.5 on 2022-06-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite_user_created_at_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='question',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
