# Generated by Django 4.0.5 on 2022-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_answers',
            field=models.ManyToManyField(related_name='favorite_answers', to='api.answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_questions',
            field=models.ManyToManyField(related_name='favorite_questions', to='api.question'),
        ),
    ]
