# Generated by Django 4.0.5 on 2022-06-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='favorite',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_favorite', to='api.favorite'),
        ),
    ]
