# Generated by Django 4.0.5 on 2022-06-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_answer_slug_alter_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
    ]
